name: Video Processor
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install pyrogram tgcrypto firebase-admin requests
      - name: Run Processor
        run: python bot.py
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
